apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poc-keycloak-angular
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
spec:
  rules:
    - host: k8s.oferto.io
      http:
        paths:
          - path: /keycloak-angular(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: poc-keycloak-angular
                port:
                  number: 80